name: "Malware_Detection"
n_gpu: 1

arch:
    type: "SVMClassificationModel"
    args: {}

data_loader:
    type: "MalwareDetectionDataLoader"
    args:
        data_dir: "data/dataset/unziped"
        metadata_path: "data/metadata.csv"
        batch_size: 128
        shuffle: true
        validation_split: 0.1
        num_workers: 2

optimizer:
    type: "Adam"
    args:
        lr: 1e-3
        weight_decay: 0
        amsgrad: True

loss: "nll_loss"
metrics: [
    "accuracy", "top_k_acc"
]

lr_scheduler:
    type: "StepLR"
    args:
        step_size: 50
        gamma: 0.1

trainer:
    epochs: 3
    save_dir: "saved/"
    save_period: 1
    verbosity: 2

    monitor: ["min", "val_loss"]
    early_stop: 10

    tensorboard: True